### ISSUE TITLE
geoip problem if i am on localhost ?

### ISSUE THREAD

**Issue by comonier** [HortonworksUniversity/Essentials#4]
[21:01:37] [User Authenticator #2/INFO]: UUID of player comonier is 231d3715-79e5-3319-bbeb-fd7671b2f412
[21:01:45] [Server thread/INFO]: comonier[/xxx.xxx.xxx.xx:61408] logged in with entity id 6964 at ([world]1.0, 63.1, 7.0)
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/INFO]: IO Exception
[21:01:45] [Craft Scheduler Thread - 244/WARN]: Error seeking country while seeking 3232285215
[21:01:45] [Craft Scheduler Thread - 244/WARN]: [Essentials] Plugin Essentials vTeamCity generated an exception while executing task 1088
java.lang.ArrayIndexOutOfBoundsException: -16776960
	at com.maxmind.geoip.LookupService.getCountry(LookupService.java:482) ~[?:?]
	at com.maxmind.geoip.LookupService.getCountry(LookupService.java:445) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.delayedJoin(EssentialsGeoIPPlayerListener.java:86) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener$1.run(EssentialsGeoIPPlayerListener.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by lestermartin** [comment]
not sure what this is about, but if there's a legitimate concern with this project, please advise.  thanks, lester
